version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "fabric-loom"
      - dependency-name: "net.fabricmc.fabric-api:fabric-api"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      